---
title: "SQL databases and R"
format: pdf
editor: visual
---
```{r}
#install.packages("tidyverse")
#install.packages("dbplyr")
#install.packages("RSQLite")
library(RSQLite)
library(tidyverse)
```

## The portal_mammals database
```{r}
dir.create("data_raw", showWarnings = FALSE)
download.file(url = "https://ndownloader.figshare.com/files/2292171",
              destfile = "data_raw/portal_mammals.sqlite", mode = "wb")
```
## Connecting to databases
```{r}
library(dplyr)
library(dbplyr)
```

```{r}
mammals <- DBI::dbConnect(RSQLite::SQLite(), "data_raw/portal_mammals.sqlite")
```

```{r}
## A closer look at how connected mammals database looks like
src_dbi(mammals)

#three tables: plots, species, surveys
```

```{r}
## Querying the database with the SQL syntax
tbl(mammals, sql("SELECT year, species_id, plot_id FROM surveys"))
```

```{r}
## Querying the database with the dplyr syntax
surveys <- tbl(mammals, "surveys")
surveys %>%
    select(year, species_id, plot_id)
```


```{r}
## look first ten observations 
head(surveys, n = 10)
```

```{r}
# difference between read_csv and database
nrow(surveys)
```
```{r}
#SQL translation
show_query(head(surveys, n = 10))
```
## Simple database queries
```{r}
surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
```
## Laziness
```{r}
## dplyr never pulls data into R unless you explicitly ask for it
data_subset <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

data_subset %>%
  select(-sex)
```

```{r}
# To retrieve all of the query results from the database, we add the collect() command to our pipe
data_subset <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight) %>%
  collect()
data_subset
```
## Complex database queries
```{r}
plots <- tbl(mammals, "plots")
plots
```
```{r}
## The plot_id column also features in the surveys table
surveys
```
```{r}
## Inner join
plots %>%
  filter(plot_id == 1) %>%
  inner_join(surveys) %>%
  collect()
```
 
```{r}
## Left Join
species <- tbl(mammals, "species")
unique_genera <- left_join(surveys, plots) %>%
    left_join(species) %>%
    group_by(plot_type) %>%
    summarize(
        n_genera = n_distinct(genus)
    ) %>%
    collect()
```
## Creating a new SQLite database
```{r}
## download files 
download.file("https://ndownloader.figshare.com/files/3299483",
              "data_raw/species.csv")
download.file("https://ndownloader.figshare.com/files/10717177",
              "data_raw/surveys.csv")
download.file("https://ndownloader.figshare.com/files/3299474",
              "data_raw/plots.csv")
```
```{r}
## import files 
species <- read_csv("data_raw/species.csv")
surveys <- read_csv("data_raw/surveys.csv")
plots <- read_csv("data_raw/plots.csv")
```











